### ISSUE TITLE
Class 'PHPMailer' not found

### ISSUE THREAD

**Issue by splattner** [splattner/myvbc#75]
```
Error: Class 'PHPMailer' not found
#9 /model/notification.model.php(54): splattner\myvbc\models\MNotification::newNotification
#8 /services/ServiceNotification.php(16): splattner\myvbc\services\ServiceNotification::addNewNotification
#7 /services/ServiceNotification.php(117): splattner\myvbc\services\ServiceNotification::addChangeAddressNotification
#6 /model/person.model.php(243): splattner\myvbc\models\MPerson::update
#5 /plugins/persondata.plugin.php(161): splattner\myvbc\plugins\PPersondata::editEntry
#4 /plugins/persondata.plugin.php(32): splattner\myvbc\plugins\PPersondata::run
#3 /pages/myteam.page.php(119): splattner\myvbc\pages\PageMyteam::editAction
#2 /vendor/splattner/framework/src/Page.php(178): splattner\framework\Page::work
#1 /vendor/splattner/framework/src/Application.php(267): splattner\framework\Application::run
#0 /index.php(52): null
```

**Comment by splattner** [comment]
closed with #76
